-- Tabela para Alertas
CREATE TABLE ALERTA (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR2(50) NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL,
    LATITUDE NUMBER NOT NULL,
    LONGITUDE NUMBER NOT NULL,
    STATUS VARCHAR2(50) DEFAULT 'Em análise' NOT NULL,
    DATA_OCORRENCIA VARCHAR2(100) NOT NULL
);

-- Tabela para Usuarios
CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(255) NOT NULL
);

-- Tabela para Regioes
CREATE TABLE REGIAO (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);








